Algoritmo "EXEMPLO-ESTRUTURA-DE-REPETICAO-ENQUANTO2"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/03/2024
Var

   contadora:inteiro

Inicio
   enquanto contadora < 10 faca
      Escreval("Gabriel do Amaral Alves")
      contadora <- contadora + 1
   fimenquanto

Fimalgoritmo