Algoritmo "EX-02-SUBTRACAO"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : subtracao do numero digitado
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 14/03/2024
Var
num1, num2, subtracao:inteiro


Inicio
escreval ("Digite o primeiro numero:")
leia(num1)
escreval ("Digite o segundo numero:")
leia(num2)
subtracao <- num1-num2
escreval ("O resultado da sua subtracao e",subtracao)
Fimalgoritmo