Algoritmo "EX-04-DIVISAO"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : multiplicacao do numero digitado
// Autor(a)    : Gabriel do Amaral Alves
// Data atual  : 14/03/2024
Var
num1, num2, divisao:real


Inicio
escreval ("Digite o primeiro numero:")
leia(num1)
escreval ("Digite o segundo numero:")
leia(num2)
divisao <- num1/num2
escreval ("O resultado da sua divisao e",divisao)
Fimalgoritmo