Algoritmo "EX-12-CELSIUS-PARA-FAHRENHEIT"
// Disciplina   : [Logica de programacao com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Calcula preco final do carro aplicando impostos
// Autor(a)    : Gabriel Do Amaral Alves
// Data atual  : 17/03/2024
Var
f, calculo:real


Inicio
Escreval("Digite a temperatura em Fahrenheit: ")
leia(f)
calculo <- (f - 32) / 1.8
Escreval("A sua temperatura em Celsius fica:",calculo)


Fimalgoritmo